---
exclude_paths:
  - "demo/**"
  - "docs/**"
  - "profiling/**"
  - "tests/**"
  - "tests/data/**"
  - "**/*.ipynb"

engines:
  duplication:
    exclude_paths:
      - "tests/**"
  metric:
    exclude_paths:
      - "tests/**"
      - "profiling/**"
