site_name: agtools
site_url: "https://github.com/Vini2/agtools"
site_author: "Vijini Mallawaarachchi"
repo_url: "https://github.com/Vini2/agtools"
repo_name: 'GitHub'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - text
        - python
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - css/extra.css
nav:
  - Home:
      - Introduction: index.md
  - Getting Started:
      - Installation: install.md
      - Quick Start: quickstart.md
  - Guides:
      - CLI Examples:
        - Obtaining stats: examples/stats.md
        - Renaming elements: examples/rename.md
        - Concatenating multiple graphs: examples/concat.md
        - Filtering segments: examples/filter.md
        - Cleaning a graph file: examples/clean.md
        - Get component of a segment: examples/component.md
        - Format conversion: examples/formatconv.md
      - API Tutorial: tutorial.md
  - Reference:
      - CLI Commands: cli.md
      - API Documentation: api.md
      - File Formats: fileformats.md
  - Support:
      - FAQ: faq.md
      - Changelog: changelog.md